### ISSUE TITLE
Hacer que el código corra en colab

### ISSUE THREAD

**Issue by nselem** [MarielChaveste/FractalBioMat#2]
- [x] Instalar con ayuda de Luis las librerías que necesites 
en colab https://stackoverflow.com/questions/55253498/how-do-i-install-a-library-permanently-in-colab
- [x] Hacer que el código de Azpeitia corra
- [ ] Hacer que el código de Pedro corra

**Comment by MarielChaveste** [comment]
No corrieron los comandos para generar los gráficos en Google Colab

**Comment by nselem** [comment]
Está esta lbrería de [L systems en Java script](https://p5js.org/examples/simulate-l-systems.html)
